### ISSUE TITLE
[Feature] use current filepath instead of hardcoded path

### ISSUE THREAD

**Issue by Idrinth** [Numeriku/warhammerdxvk#1]
Might be the solution https://www.windows-commandline.com/batch-file-get-current-directory/

**Comment by Numeriku** [comment]
I guess i can make it so that the bat file is run from the warhammer folder itself and remove all hardcoded links so its easier for users.

**Comment by Numeriku** [comment]
> Might be the solution https://www.windows-commandline.com/batch-file-get-current-directory/

Thank you, i updated the code to use the idea from that link.
